
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cacerts.csi.appscode.com
  resources:
  - caproviderclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cacerts.csi.appscode.com
  resources:
  - caproviderclasses/finalizers
  verbs:
  - update
- apiGroups:
  - cacerts.csi.appscode.com
  resources:
  - caproviderclasses/status
  verbs:
  - get
  - patch
  - update
